"""
Generate the MNIST artifacts consumed by the example programs.

Writes into the directory containing this script:

- mnist_train_x.npy, mnist_train_y.npy  (full MNIST, one-hot labels) — used by
  mlp_mnist_float32_host and mlp_mnist_asym_host.
- mnist_test_x.npy, mnist_test_y.npy    (full MNIST test split)
- mnist_train_subset.h / mnist_test_subset.h  (compile-time uint8 subsets +
  integer class labels) — used by the *_mcu examples and by mnist_inference.

Downloads the IDX-formatted MNIST files from a Google Cloud mirror on first
use and caches them next to this script. Only depends on numpy.

Run via:
    uv run src/examples/data/generate_subset.py
    # override defaults if you want:
    uv run src/examples/data/generate_subset.py --train-subset 200 --test-subset 50
"""

import argparse
import gzip
import os
import urllib.request
from pathlib import Path

import numpy as np


MNIST_BASE_URL = "https://storage.googleapis.com/cvdf-datasets/mnist"
MNIST_FILES = {
    "train_images": "train-images-idx3-ubyte.gz",
    "train_labels": "train-labels-idx1-ubyte.gz",
    "test_images":  "t10k-images-idx3-ubyte.gz",
    "test_labels":  "t10k-labels-idx1-ubyte.gz",
}

NUM_CLASSES = 10
IMG_W = 28
IMG_H = 28


def download(url: str, dest: Path) -> None:
    if dest.exists():
        return
    print(f"  downloading {url}")
    urllib.request.urlretrieve(url, dest)


def load_idx_images(path: Path) -> np.ndarray:
    with gzip.open(path, "rb") as f:
        magic = int.from_bytes(f.read(4), "big")
        assert magic == 0x0803, f"unexpected magic for images: {magic:#x}"
        n = int.from_bytes(f.read(4), "big")
        rows = int.from_bytes(f.read(4), "big")
        cols = int.from_bytes(f.read(4), "big")
        data = np.frombuffer(f.read(), dtype=np.uint8).reshape(n, rows, cols)
    return data


def load_idx_labels(path: Path) -> np.ndarray:
    with gzip.open(path, "rb") as f:
        magic = int.from_bytes(f.read(4), "big")
        assert magic == 0x0801, f"unexpected magic for labels: {magic:#x}"
        n = int.from_bytes(f.read(4), "big")
        data = np.frombuffer(f.read(), dtype=np.uint8)
        assert data.shape == (n,)
    return data


def load_mnist(out_dir: Path):
    for key, fname in MNIST_FILES.items():
        download(f"{MNIST_BASE_URL}/{fname}", out_dir / fname)
    train_images = load_idx_images(out_dir / MNIST_FILES["train_images"])
    train_labels = load_idx_labels(out_dir / MNIST_FILES["train_labels"])
    test_images  = load_idx_images(out_dir / MNIST_FILES["test_images"])
    test_labels  = load_idx_labels(out_dir / MNIST_FILES["test_labels"])
    return (train_images, train_labels), (test_images, test_labels)


def to_float_nchw(images_u8: np.ndarray) -> np.ndarray:
    """uint8 HxW -> float32 [N, 1, H, W] in [0, 1], matching torchvision.ToTensor()."""
    return (images_u8.astype(np.float32) / 255.0)[:, None, :, :]


def to_onehot(labels: np.ndarray) -> np.ndarray:
    oh = np.zeros((labels.size, NUM_CLASSES), dtype=np.float32)
    oh[np.arange(labels.size), labels] = 1.0
    return oh


def save_npy(out_dir: Path, split: str, images_u8: np.ndarray, labels: np.ndarray) -> None:
    x = to_float_nchw(images_u8)
    y = to_onehot(labels)
    np.save(out_dir / f"mnist_{split}_x.npy", x)
    np.save(out_dir / f"mnist_{split}_y.npy", y)
    print(f"  wrote mnist_{split}_x.npy  shape={x.shape}")
    print(f"  wrote mnist_{split}_y.npy  shape={y.shape}")


def write_subset_header(
    path: Path,
    name: str,
    images_u8: np.ndarray,
    labels: np.ndarray,
    guard: str,
    features: int,
) -> None:
    n = images_u8.shape[0]
    flat_u8 = images_u8.reshape(n, features)
    labels_u8 = labels.astype(np.uint8)

    with path.open("w") as f:
        f.write("/* Auto-generated by generate_subset.py. Do not edit by hand. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {name.upper()}_SIZE     {n}\n")
        f.write(f"#define {name.upper()}_FEATURES {features}\n\n")
        f.write(f"static const uint8_t {name}_images[{name.upper()}_SIZE * "
                f"{name.upper()}_FEATURES] = {{\n")
        flat = flat_u8.reshape(-1)
        for i in range(0, flat.size, 16):
            row = ", ".join(str(int(v)) for v in flat[i : i + 16])
            f.write(f"    {row},\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t {name}_labels[{name.upper()}_SIZE] = {{\n    ")
        f.write(", ".join(str(int(v)) for v in labels_u8))
        f.write("\n};\n\n")
        f.write(f"#endif /* {guard} */\n")
    print(f"  wrote {path.name}  n={n}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train-subset", type=int, default=100,
                        help="Samples in mnist_train_subset.h (default 100).")
    parser.add_argument("--test-subset", type=int, default=20,
                        help="Samples in mnist_test_subset.h (default 20).")
    parser.add_argument("--seed", type=int, default=0,
                        help="RNG seed for subset selection.")
    args = parser.parse_args()

    out_dir = Path(__file__).resolve().parent
    os.makedirs(out_dir, exist_ok=True)
    print(f"Output directory: {out_dir}")

    (train_x_u8, train_y), (test_x_u8, test_y) = load_mnist(out_dir)

    save_npy(out_dir, "train", train_x_u8, train_y)
    save_npy(out_dir, "test",  test_x_u8,  test_y)

    rng = np.random.default_rng(args.seed)
    train_idx = rng.choice(len(train_x_u8), size=args.train_subset, replace=False)
    test_idx  = rng.choice(len(test_x_u8),  size=args.test_subset,  replace=False)

    write_subset_header(
        out_dir / "mnist_train_subset.h",
        "mnist_train_subset",
        train_x_u8[train_idx],
        train_y[train_idx],
        "MNIST_TRAIN_SUBSET_H",
        IMG_W * IMG_H,
    )
    write_subset_header(
        out_dir / "mnist_test_subset.h",
        "mnist_test_subset",
        test_x_u8[test_idx],
        test_y[test_idx],
        "MNIST_TEST_SUBSET_H",
        IMG_W * IMG_H,
    )

    print("Done.")


if __name__ == "__main__":
    main()
